### ISSUE TITLE
brew python@3.6 failing

### ISSUE THREAD

**Issue by dhingra** [sashkab/homebrew-python#139] opened 2022-03-23 03:51 UTC
Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
**MacOS 12.3 Apple M1**

% **brew install sashkab/python/python@3.6**   
==> Downloading https://pypi.org/packages/source/s/setuptools/setuptools-58.0.3.tar.gz
==> Downloading from https://files.pythonhosted.org/packages/6d/f2/85d487d516e7319fad8052a6bb4a4447244e59f830d17515fb40d3141072/setuptools-58.0.3.tar.gz
######################################################################## 100.0%
==> Downloading https://www.pypi.org/packages/source/p/pip/pip-21.2.4.tar.gz
==> Downloading from https://files.pythonhosted.org/packages/52/e1/06c018197d8151383f66ebf6979d951995cf495629fc54149491f5d157d0/pip-21.2.4.tar.gz
######################################################################## 100.0%
==> Downloading https://pypi.org/packages/source/w/wheel/wheel-0.37.0.tar.gz
==> Downloading from https://files.pythonhosted.org/packages/4e/be/8139f127b4db2f79c8b117c80af56a3078cc4824b5b94250c7f81a70e03b/wheel-0.37.0.tar.gz
######################################################################## 100.0%
==> Downloading https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tar.xz
######################################################################## 100.0%
==> Installing python@3.6 from sashkab/python
==> ./configure --prefix=/opt/homebrew/Cellar/python@3.6/3.6.15 --enable-ipv6 --datarootdir=/opt/homebrew/Cellar/python@3.6/3.6.15/share --datadir=/opt/homebrew/Cellar/python@3.6/3.6.15/share --enable-framework=/opt/homebrew/Cellar/python@3.6/3.
Last 15 lines from /Users/rdhingra/Library/Logs/Homebrew/python@3.6/01.configure:
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for a sed that does not truncate output... /usr/bin/sed
checking for --with-cxx-main=<compiler>... no
checking for the platform triplet based on compiler characteristics... darwin
**configure: error: internal configure error for the platform triplet, please file a bug report**

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sashkab/homebrew-python/issues

**Comment by sashkab** [comment] 2022-03-23 14:25
Duplicate of #138 and #137.

**Closed as completed by sashkab** 2022-03-23 14:25 UTC
