### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by SurenNihalani** [sashkab/homebrew-python#138] opened 2022-02-20 01:10 UTC
~/code/renaissance master   ODRL97H-M
brew install sashkab/python/python@3.6                                                                                                                               -130-
==> Tapping sashkab/python
Cloning into '/opt/homebrew/Library/Taps/sashkab/homebrew-python'...
remote: Enumerating objects: 1499, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 1499 (delta 87), reused 116 (delta 56), pack-reused 1348
Receiving objects: 100% (1499/1499), 344.69 KiB | 1.35 MiB/s, done.
Resolving deltas: 100% (807/807), done.
Tapped 3 formulae (18 files, 435.4KB).
==> Downloading https://pypi.org/packages/source/s/setuptools/setuptools-58.0.3.tar.gz
==> Downloading from https://files.pythonhosted.org/packages/6d/f2/85d487d516e7319fad8052a6bb4a4447244e59f830d17515fb40d3141072/setuptools-58.0.3.tar.gz
######################################################################## 100.0%
==> Downloading https://www.pypi.org/packages/source/p/pip/pip-21.2.4.tar.gz
==> Downloading from https://files.pythonhosted.org/packages/52/e1/06c018197d8151383f66ebf6979d951995cf495629fc54149491f5d157d0/pip-21.2.4.tar.gz
######################################################################## 100.0%
==> Downloading https://pypi.org/packages/source/w/wheel/wheel-0.37.0.tar.gz
==> Downloading from https://files.pythonhosted.org/packages/4e/be/8139f127b4db2f79c8b117c80af56a3078cc4824b5b94250c7f81a70e03b/wheel-0.37.0.tar.gz
######################################################################## 100.0%
==> Downloading https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tar.xz
######################################################################## 100.0%
==> Installing python@3.6 from sashkab/python
==> ./configure --prefix=/opt/homebrew/Cellar/python@3.6/3.6.15 --enable-ipv6 --datarootdir=/opt/homebrew/Cellar/python@3.6/3.6.15/share --datadir=/opt/homebrew/Cellar/pyt
Last 15 lines from /Users/skn/Library/Logs/Homebrew/python@3.6/01.configure:
checking size of float... 4
checking size of double... 8
checking size of fpos_t... 8
checking size of size_t... 8
checking size of pid_t... 4
checking size of uintptr_t... 8
checking for long double support... yes
checking size of long double... 8
checking size of _Bool... 1
checking size of off_t... 8
checking whether to enable large file support... no
checking size of time_t... 8
checking for pthread_t... yes
checking size of pthread_t... 8
configure: error: Unexpected output of 'arch' on OSX

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sashkab/homebrew-python/issues

**Comment by sashkab** [comment] 2022-02-20 01:18
Python 3.6 is not supported on macOS with arm architecture, based on paths seen in the output above. Please use Python 3.8 or newer.

**Comment by sashkab** [comment] 2022-02-20 01:19
Duplicate of #137.

**Closed as completed by sashkab** 2022-02-20 01:18 UTC
Labels: wontfix
